/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author sergio
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private File file;
    private String archivo;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        btnFileChooser = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRegLibro = new javax.swing.JLabel();
        lblRegEstudiante = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblPrestamo = new javax.swing.JLabel();
        lblMensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo.setText("Biblioteca");

        txtPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPathActionPerformed(evt);
            }
        });

        btnFileChooser.setText("...");
        btnFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileChooserActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese el Archivo que desea Cargar");

        lblRegLibro.setBackground(java.awt.Color.lightGray);
        lblRegLibro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRegLibro.setForeground(java.awt.Color.black);
        lblRegLibro.setText("Registrar Libro");
        lblRegLibro.setOpaque(true);
        lblRegLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegLibroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegLibroMouseEntered(evt);
            }
        });

        lblRegEstudiante.setBackground(java.awt.Color.lightGray);
        lblRegEstudiante.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRegEstudiante.setForeground(java.awt.Color.black);
        lblRegEstudiante.setText("Registrar Estudiante");
        lblRegEstudiante.setOpaque(true);
        lblRegEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegEstudianteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegEstudianteMouseEntered(evt);
            }
        });

        lblReportes.setBackground(java.awt.Color.lightGray);
        lblReportes.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblReportes.setForeground(java.awt.Color.black);
        lblReportes.setText("Generar Reportes");
        lblReportes.setOpaque(true);
        lblReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportesMouseEntered(evt);
            }
        });

        lblPrestamo.setBackground(java.awt.Color.lightGray);
        lblPrestamo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblPrestamo.setForeground(java.awt.Color.black);
        lblPrestamo.setText("Realizar Prestamo");
        lblPrestamo.setOpaque(true);
        lblPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPrestamoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPrestamoMouseEntered(evt);
            }
        });

        lblMensajeError.setForeground(new java.awt.Color(245, 6, 6));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCargar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRegLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lblRegLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFileChooser)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCargar)
                            .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRegEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPathActionPerformed

    private void btnFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileChooserActionPerformed
        txtPath.setText(BuscarDireccion());
    }//GEN-LAST:event_btnFileChooserActionPerformed

    private void lblRegLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegLibroMouseEntered
        lblRegLibro.setBackground(Color.white);
    }//GEN-LAST:event_lblRegLibroMouseEntered

    private void lblRegLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegLibroMouseExited
        lblRegLibro.setBackground(Color.lightGray);
    }//GEN-LAST:event_lblRegLibroMouseExited

    private void lblRegEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegEstudianteMouseEntered
         lblRegEstudiante.setBackground(Color.white);
    }//GEN-LAST:event_lblRegEstudianteMouseEntered

    private void lblPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrestamoMouseEntered
        lblPrestamo.setBackground(Color.white);
    }//GEN-LAST:event_lblPrestamoMouseEntered

    private void lblReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseEntered
        lblReportes.setBackground(Color.white);
    }//GEN-LAST:event_lblReportesMouseEntered

    private void lblRegEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegEstudianteMouseExited
       lblRegEstudiante.setBackground(Color.lightGray);
    }//GEN-LAST:event_lblRegEstudianteMouseExited

    private void lblPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrestamoMouseExited
        lblPrestamo.setBackground(Color.lightGray);
    }//GEN-LAST:event_lblPrestamoMouseExited

    private void lblReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseExited
        lblReportes.setBackground(Color.lightGray);
    }//GEN-LAST:event_lblReportesMouseExited

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        if(file==null){
            lblMensajeError.setText("Este Archivo No Existe");
        }else{
            if(file.isFile()){
                try {
                    ManejadorDeArchivos.cargarArchivo(file);
                } catch (IOException ex) {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                lblMensajeError.setText("Elija un Archivo .txt");
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    private String BuscarDireccion(){
    JFileChooser buscador = new JFileChooser();    
    buscador.setFileSelectionMode(JFileChooser.FILES_ONLY);
    buscador.showOpenDialog(this);
    file = buscador.getSelectedFile();
    if(file == null){
        archivo="";        
    }else{
    archivo = buscador.getSelectedFile().getAbsolutePath();  
    }
    return archivo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JLabel lblRegEstudiante;
    private javax.swing.JLabel lblRegLibro;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
